apiVersion: v1
kind: Secret
metadata:
  name: payments-secret
type: Opaque
stringData:
  RabbitMq__Username: guest
  RabbitMq__Password: guest
  Jwt__Secret: "KkR.cX]N=8Y3=%uqJJgPD+}K^f?cKnmchVFm-qfa3rUBjBU!G^1L8cn1nEvhv+*"
  ConnectionStrings__DefaultConnection: "Server=payments-sqlserver,1433;Database=FiapCloudGamesPayments;User Id=sa;Password=Payments!Passw0rd;TrustServerCertificate=True"
